version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      # Install Snyk
      - echo Install Snyk
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk
      # Snyk auth
      # - ./snyk config set api="$SNYK_AUTH_TOKEN"
      # Build Docker image for testing
      - echo Build client and server docker images for testing...
      - docker build -t neurobica/react-test -f ./client/Dockerfile.dev ./client
      - docker build -t neurobica/nodejs-test -f ./server/Dockerfile.dev ./server
  build:
    commands:
      - echo Build started on `date`
      # Run tests with built Docker images
      - echo Run react tests...
      - docker run -e CI=true neurobica/react-test
      - echo Run nodejs tests...
      - docker run -e CI=true neurobica/nodejs-test
      # Scan Docker image with Snyk
      ## Client
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker neurobica/react-test:latest --file=./client/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker neurobica/react-test:latest --file=./client/Dockerfile.dev
      ## server
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker neurobica/nodejs-test:latest --file=./server/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker neurobica/nodejs-test:latest --file=./server/Dockerfile.dev
      # Build the Docker images
      - echo Building the production Docker image...
      - docker build -t neurobica/dkr-multicontainer-app-client ./client
      - docker build -t neurobica/dkr-multicontainer-app-server ./server
      - docker build -t neurobica/dkr-multicontainer-app-nginx ./nginxmichaelproxy
      # Log in to the Docker CLI
      - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push neurobica/dkr-multicontainer-app-client
      - docker push neurobica/dkr-multicontainer-app-server
      - docker push neurobica/dkr-multicontainer-app-nginx
