version: "3.8"
services:
  nginx:
    depends_on:
      - frontend
      - server
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile.dev
      context: ./nginxmichaelproxy
    ports:
      - "6444:6444"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/react-docker:delegated
      - /node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    #ports:
    #  - '3001:3001'
    restart: on-failure
    container_name: server
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    env_file:
      - ./server/.env
