version: "3.8"
services:
  nginx:
    depends_on:
      - client
      - server
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ./nginxmichaelproxy
    ports:
      - "80:443"
  client:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - '3000:3000'
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    restart: on-failure
    container_name: client
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    #ports:
    #  - '3001:3001'
    restart: on-failure
    container_name: server
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    env_file:
      - ./server/.env
